name: PHPUnit Tests

on:
  push:
    branches:
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
    tags:
      - '[0-9]+.[0-9]'
      - '[0-9]+.[0-9].[0-9]+'
  pull_request:
    branches:
      - trunk
      - '3.[7-9]'
      - '[4-9].[0-9]'
  workflow_dispatch:
  # Once weekly On Sundays at 00:00 UTC.
  schedule:
    - cron: '0 0 * * 0'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  #
  # Creates a PHPUnit test job for each PHP/MySQL combination.
  #
  test-with-mysql:
    name: PHP ${{ matrix.php }}
    uses: WordPress/wordpress-develop/.github/workflows/reusable-phpunit-tests-v3.yml@trunk
    permissions:
      contents: read
    secrets: inherit
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.3' ]
        db-type: [ 'mysql' ]
        db-version: [ '5.7', '8.0', '8.4', '9.0' ]
        tests-domain: [ 'example.org' ]
        multisite: [ false, true ]
        memcached: [ false ]

        include:
          # Include jobs that test with memcached.
          - os: ubuntu-latest
            php: '8.3'
            db-type: 'mysql'
            db-version: '8.4'
            tests-domain: 'example.org'
            multisite: false
            memcached: true
          - os: ubuntu-latest
            php: '8.3'
            db-type: 'mysql'
            db-version: '8.4'
            tests-domain: 'example.org'
            multisite: true
            memcached: true

        exclude:
          # MySQL 9.0+ will not work on PHP 7.2 & 7.3. See https://core.trac.wordpress.org/ticket/61218.
          - php: '7.2'
            db-version: '9.0'
          - php: '7.3'
            db-version: '9.0'

    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      phpunit-config: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}
      tests-domain: ${{ matrix.tests-domain }}
      report: ${{ matrix.report || false }}

  #
  # Creates a PHPUnit test job for each PHP/MariaDB combination.
  #
  test-with-mariadb:
    name: PHP ${{ matrix.php }}
    uses: WordPress/wordpress-develop/.github/workflows/reusable-phpunit-tests-v3.yml@trunk
    permissions:
      contents: read
    secrets: inherit
    if: ${{ github.repository == 'WordPress/wordpress-develop' || github.event_name == 'pull_request' }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        php: [ '8.3' ]
        db-type: [ 'mariadb' ]
        db-version: [ '10.4', '10.6', '10.11', '11.2' ]
        multisite: [ false, true ]
        memcached: [ false ]

        include:
        # Include jobs that test with memcached.
        - os: ubuntu-latest
          php: '8.3'
          db-type: 'mariadb'
          db-version: '11.2'
          multisite: false
          memcached: true
        - os: ubuntu-latest
          php: '8.3'
          db-type: 'mariadb'
          db-version: '11.2'
          multisite: true
          memcached: true
    with:
      os: ${{ matrix.os }}
      php: ${{ matrix.php }}
      db-type: ${{ matrix.db-type }}
      db-version: ${{ matrix.db-version }}
      multisite: ${{ matrix.multisite }}
      memcached: ${{ matrix.memcached }}
      phpunit-config: ${{ matrix.multisite && 'tests/phpunit/multisite.xml' || 'phpunit.xml.dist' }}
      report: ${{ matrix.report || false }}

