name: Lint GitHub Actions workflows
on:
  workflow_call:

permissions: {}

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      # https://github.com/rhysd/actionlint
      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.7
        with:
          args: "-color -verbose"
